### ISSUE TITLE
Multiprocessing not working

### ISSUE THREAD

**Issue by sepehr78** [CJWorkbench/pyspawner#1]
It appears that a sandboxed process cannot use functionality of the multiprocessing module. Consider the following simple example taken from [Python docs](https://docs.python.org/3/library/multiprocessing.html) that launches multiple processes to compute the element-wise square of a list:

    from multiprocessing import Pool
    def f(x):
        return x * x
    
    
    def multiproc_test():
		try:   
		    with Pool(5) as p:  
		        sys.stdout.write(f"{p.map(f, [1, 2, 3])}\n")  
		except Exception as e:  
		    sys.stdout.write(f"ERROR: {e}\n")  
		    sys.stdout.write(traceback.format_exc())
Calling `multiproc_test` from a non-sandboxed script works as expected and prints `[1, 4, 9]` as expected. However, when I call it from a sandboxed script using the following code:

    client = pyspawner.Client(  
      child_main="mymodule.multiproc_test",  
      preload_imports=["multiprocessing.pool", "multiprocessing", "multiprocessing.queues",  
      "multiprocessing.synchronize"]  
    )  
      
    child_process = client.spawn_child(  
      process_name="child-1",  
      sandbox_config=pyspawner.SandboxConfig(  
      chroot_dir=Path(path.join(os.getcwd(), "child_dir"))  
     ))
     
     while True:  
	     line = child_process.stdout.readline()  
	     if not line:  
	         break  
	     print(str(line, 'utf-8').strip())  
	  
	client.close()  
	child_process.kill()
The child process throws an exception with the following traceback:

   

    Traceback (most recent call last):
    File "/home/sepehr/Documents/pyspawner/experimental/spawner/mymodule.py", line 61, in multiproc_test
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/pool.py", line 191, in __init__
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/pool.py", line 343, in _setup_queues
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    File "/home/sepehr/anaconda3/envs/pyspawner/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    OSError: [Errno 38] Function not implemented
I found a similar issue discussed [here](https://sysadmins.co.za/parallel-processing-on-aws-lambda-with-python-using-multiprocessing/) and the explanation is that the error occurs when shared memory for processes is not supported. So is this a limitation of PySpawner or is there something else that needs to be done to get it to work?

The specs of my setup are given below:

    OS:  Ubuntu 20.04.1 LTS (GNU/Linux 5.8.0-41-generic x86_64)
    Python enviornment: Anaconda with Python 3.8.5
Thanks in advance :)

**Comment by adamhooper** [comment]
Python `multiprocessing.Queue` uses the C library's `sem_open()`. glibc's `sem_open()` [returns `ENOSYS` ](https://github.com/walac/glibc/blob/master/nptl/sem_open.c) if:

* There is no `tmpfs` mounted at `/dev/shm`
* And failing that, it cannot read `/proc/mounts`

@sepehr78 if you create a special chroot that has a `tmpfs` mounted in its `/dev/shm`, does your example work? (Primer: `mkdir -p child_dir/dev/shm && sudo mount -t tmpfs tmpfs child_dir/dev/shm`)

This tmpfs requirement is specific to glibc. I think musl only requires the directory `/dev/shm` to be present but [doesn't force a filesystem](https://github.com/bpowers/musl/blob/94cb2ec2a0ffcb47d24dbf7a30e462505396cf54/src/mman/shm_open.c).

**Comment by sepehr78** [comment]
> Python `multiprocessing.Queue` uses the C library's `sem_open()`. glibc's `sem_open()` [returns `ENOSYS` ](https://github.com/walac/glibc/blob/master/nptl/sem_open.c) if:
> 
> * There is no `tmpfs` mounted at `/dev/shm`
> * And failing that, it cannot read `/proc/mounts`
> 
> @sepehr78 if you create a special chroot that has a `tmpfs` mounted in its `/dev/shm`, does your example work? (Primer: `mkdir -p child_dir/dev/shm && sudo mount -t tmpfs tmpfs child_dir/dev/shm`)
> 
> This tmpfs requirement is specific to glibc. I think musl only requires the directory `/dev/shm` to be present but [doesn't force a filesystem](https://github.com/bpowers/musl/blob/94cb2ec2a0ffcb47d24dbf7a30e462505396cf54/src/mman/shm_open.c).

I tried creating a `/dev/shm` directory inside the chroot and also mounting it as you mentioned. The code does not throw an OSError or any exception actually and just hangs and nothing gets printed to stdout.

**Comment by adamhooper** [comment]
@sepehr78 I'm inclined to suspect this hanging is a problem on the caller side of things.

Reading from a process's stdout+stderr+pid is no easy task. Try copying `_spawn_and_communicate()` from `tests/test_client.py`. It won't work in production code, but it's enough to capture a stack trace if need be.
